/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Conditional#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Conditional#getValue2 <em>Value2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Conditional#getValue3 <em>Value3</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getConditional_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Conditional#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' attribute.
   * @see #setValue2(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getConditional_Value2()
   * @model
   * @generated
   */
  int getValue2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Conditional#getValue2 <em>Value2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value2</em>' attribute.
   * @see #getValue2()
   * @generated
   */
  void setValue2(int value);

  /**
   * Returns the value of the '<em><b>Value3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value3</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value3</em>' attribute.
   * @see #setValue3(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getConditional_Value3()
   * @model
   * @generated
   */
  int getValue3();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Conditional#getValue3 <em>Value3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value3</em>' attribute.
   * @see #getValue3()
   * @generated
   */
  void setValue3(int value);

} // Conditional
